---
name: String-MatchInterpolate
version: 0.04
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: |-
  named regexp capture and interpolation from the
  same template.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Text::Balanced: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  String::MatchInterpolate:
    file: lib/String/MatchInterpolate.pm
    version: 0.04
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
