---
abstract: "named regexp capture and interpolation from the\nsame template."
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-MatchInterpolate
provides:
  String::MatchInterpolate:
    file: lib/String/MatchInterpolate.pm
    version: 0.06
requires:
  Text::Balanced: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
